---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    -  http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wapp
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wapp
  labels:
    tier: backend
spec:
  selector:
    app: wapp
    tier: backend
  ports:
    - protocol: TCP
      port: 300
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapp
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wapp
      tier: backend
  template:
    metadata:
      labels:
        app: wapp
        tier: backend
    spec:
      enableServiceLinks: false
      containers:
        - name: wapp
          image: k8s.gcr.io/e2e-test-images/echoserver:2.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

